[package]
name = "ethbind"
license-file.workspace = true
edition.workspace = true
version.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethbind-core = { path = "./core", version = "^0.1" }
ethbind-rust-macros = { path = "./macros", version = "^0.1", optional = true }

[dev-dependencies]
anyhow = "^1"

serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }

[features]
default = ["rust_macro_gen", "serde"]
rust_macro_gen = ["ethbind-rust-macros"]
serde = ["ethbind-rust-macros/serde"]

[workspace]
members = ["macros", "core", ".", "rust"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
keywords = ["ethereum", "contract", "codegen"]
description = "An ethereum contract binding code generation framework for arbitrary programming languages"
documentation = "https://docs.rs/ethbind-rs"
readme = "README.md"
homepage = "https://github.com/AgoraCyber/ethbind-rs"
repository = "https://github.com/AgoraCyber/ethbind-rs"
