name: Rust

on:
  release:
    types: [published, edited]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    environment: cargo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: publish ethbind-json
        run: cargo publish -p ethbind-json
      - name: publish ethbind-gen
        run: cargo publish -p ethbind-gen
      - name: publish ethbind-gen
        run: cargo publish -p ethbind-rust
